### PR TITLE
Fix #12

### LINKED ISSUE #12: XL User Data not loading when URL has search params
**Describe the bug**
If you load a user's profile but the URL has search params (for example `/@User?tab=repls`) the search params get caught by the RegEx and sent to GraphQL, returning `null` for the user.

**To Reproduce**
1. Go to https://replit.com/@LuisAFK?tab=repls (XL Data shouldn't load)
2. Go to https://replit.com/@LuisAFK (XL Data should load)

**Expected behavior**
The RegEx shouldn't match search params.

**Screenshots**
N/A.

**Desktop (please complete the following information):**
 - OS: MacBook Pro (15-inch, 2016)
 - Browser: Chrome
 - Version: 108.0.5359.124 (Official Build) (x86_64) 

**Additional context**
N/A.

### PR DESCRIPTION
**Pull request by 7heMech**
Fix #12

### CODE REVIEW

**Review by DillonB07 — APPROVED** [review]
Great, looks good!

@lafkpages?

**Review by lafkpages — COMMENTED** [review]
Will test this on my computer later but looks good

**Comment by lafkpages** [comment]
The new RegEx and the old one do the same thing? According to Regex101

**Comment by lafkpages** [comment]
I already fixed this by using the Next router state instead of looking at the URL. It's way more reliable.

**Pull request closed without merging**
