### PR TITLE
Remove false file

### PR DESCRIPTION
**Pull request by DillonB07**

### CODE REVIEW

**Comment by lafkpages** [comment]
What does "for straight commit" mean?

**Comment by DillonB07** [comment]
It won't create the PR when adding somebody as a contributor. Instead, it will commit automatically.

**Comment by lafkpages** [comment]
Doesn't that mean that anyone can add themselves as a contributor?

**Comment by DillonB07** [comment]
@all-contributors add @DaInfLoop as a contributor for data

**Pull request merged**
